### ISSUE TITLE
feat: keep info about invalid transactions

### ISSUE THREAD

**Issue by asiaziola** [redstone-finance/redstone-sw-gateway#42]
Maybe we should keep informations about all the SmartWeave transactions without paying attention to its validity (maybe in a separated db or just with special invalid tag).

e.g. transaction to verify DSan2S2AwuyZZwragrI_5L8RiraWjOsgMxaEpiYN2BY

**Comment by ppedziwiatr** [comment]
@asiaziola , I still don't understand WTF.

**Comment by ppedziwiatr** [comment]
this issue makes no sense ❤️
